# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_wX3xeJiV-5z8J7hkQuXN2Pjns0hE52t
"""

import pandas as pd

import numpy as np

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/annex1.csv")

item_code=df["Item Code"].to_numpy()
print(item_code)

item_name=df["Item Name"].to_numpy()
print(item_name)

category_code=df["Category Code"].to_numpy()
print(category_code)

category_name=df["Category Name"].to_numpy()
print(category_name)

print(f"Array: item_code, Type: {item_code.dtype}, Shape: {item_code.shape}")
print(f"Array: item_name, Type: {item_name.dtype}, Shape: {item_name.shape}")
print(f"Array: category_code, Type: {category_code.dtype}, Shape: {category_code.shape}")
print(f"Array: category_name, Type: {category_name.dtype}, Shape: {category_name.shape}")

# Display the columns again to confirm 'Quantity' and 'Unit Price' column names
print("DataFrame Columns for Revenue Calculation:")
print(df.columns)

# Assuming 'Sales Quantity' and 'Sale Price' are the columns for quantity and unit price respectively.
# Please adjust the column names if they are different based on the output of the previous cell.
quantity_array = df["Sales Quantity"].to_numpy()
unit_price_array = df["Sale Price"].to_numpy()

# Calculate revenue using broadcasting
revenue_array = quantity_array * unit_price_array

print(f"First 10 values of Quantity Array: {quantity_array[:10]}")
print(f"First 10 values of Unit Price Array: {unit_price_array[:10]}")
print(f"First 10 values of Revenue Array (Quantity * Unit Price): {revenue_array[:10]}")

# Calculate statistical operations on the sales array
mean_sales = np.mean(sales_array)
median_sales = np.median(sales_array)
variance_sales = np.var(sales_array)
std_dev_sales = np.std(sales_array)

print(f"Mean Sales: {mean_sales}")
print(f"Median Sales: {median_sales}")
print(f"Variance of Sales: {variance_sales}")
print(f"Standard Deviation of Sales: {std_dev_sales}")

"""### Extracting Specific Sales Records using Indexing and Slicing

We'll now use `pandas`' powerful indexing and slicing capabilities to select specific sales records from our DataFrame `df`. We'll demonstrate a few common scenarios:

1.  **Extracting records for a specific Item Code.**
2.  **Extracting records for a specific Category Name.**
3.  **Slicing to get the first N sales records.**
"""

# Example 1: Extract records for a specific Item Code
# Let's pick the first item code from our `item_code` array
specific_item_code = item_code[0]
item_sales_records = df.loc[df["Item Code"] == specific_item_code]

print(f"Sales records for Item Code {specific_item_code}:")
display(item_sales_records)

# Example 2: Extract records for a specific Category Name
# Let's pick the first category name from our `category_name` array
specific_category_name = category_name[0]
category_sales_records = df.loc[df["Category Name"] == specific_category_name]

print(f"\nSales records for Category Name '{specific_category_name}':")
display(category_sales_records)

# Example 3: Slicing to get the first 5 sales records
first_five_records = df.iloc[:5]

print("\nFirst 5 sales records:")
display(first_five_records)

# Display the columns of the DataFrame to identify the sales-related column
print("DataFrame Columns:")
print(df.columns)

# Assuming 'Sale Price' is the column containing sales data.
# Please adjust the column name if it's different based on the output of the previous cell.
sales_array = df["Sale Price"].to_numpy()

total_sales = np.sum(sales_array)
average_sales = np.mean(sales_array)

print(f"Total Sales: {total_sales}")
print(f"Average Sales: {average_sales}")